### ISSUE TITLE
UX: Display a notification when no results are found

### ISSUE THREAD

**Issue by b0o** [DNLHC/glance.nvim#14]
I was trying to `Glance definitions` on a Lua function imported from another module, but nothing was happening. I tried glancing other identifiers which worked as expected, so I am assuming the LSP server isn't finding any definitions for the first identifier I tried - I confirmed this with `vim.lsp.buf.definition()` which printed the message "Definition not found".

My suggestion: If no results are found, it'd be helpful if Glance would use `vim.notify` to let the user know rather than failing silently.

P.s. I've only been using this plugin for a few minutes and I'm already loving it! I always found `vim.lsp.buf.definition()` to be very clunky, but Glance is super intuitive. Nice work!

**Comment by DNLHC** [comment]
> My suggestion: If no results are found, it be helpful if Glance would use vim.notify to let the user know rather than failing silently.

Good suggestion, i considered adding a notification but there is a tricky part i haven't figured how to solve, when a buffer has multiple LSP clients attached some of them will return no results, so we need to notify only when all clients finished their requests. Otherwise there will be "No definition found" message even when the results are there.

> but Glance is super intuitive. Nice work!

Thank you!
